version: '3.7'

services:
  # MySQL
  mysql:
    image: mysql:5.7
    container_name: web-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./build/docker/mysql/conf.d2:/etc/mysql/conf.d
      - ./build/docker/mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gogin
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678

  # Redis
  redis:
    image: redis:5.0
    container_name: web-redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass password --appendonly yes

  # Mongo
  mongo:
    build:
      context: ./build/docker/mongo/
      dockerfile: Dockerfile
      args:
        mongo_port: 27017
    #image: mongo:4.2
    image: go-gin-wrapper-mongo:1.0
    container_name: web-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-secret
    ports:
      - "27017:27017"
    command: mongod --auth
