version: '3.9'

services:
  # MySQL
  mysql:
    ports:
      - "${MYSQL_PORT:-13306}:3306"

  # Redis
  redis:
    ports:
      - "${REDIS_PORT:-16379}:6379"

  # Golang:go-gin-wrapper
  web:
    ports:
      - "${WEB_PORT:-8080}:8080"
    volumes:
      - ./:/go/src/github.com/hiromaily/go-gin-wrapper
      #- ./cmd:/go/src/github.com/hiromaily/go-gin-wrapper/cmd
      #- ./pkg:/go/src/github.com/hiromaily/go-gin-wrapper/core
      #- ./configs:/go/src/github.com/hiromaily/go-gin-wrapper/configs
      #- ./test:/go/src/github.com/hiromaily/go-gin-wrapper/test
      #- ./web:/go/src/github.com/hiromaily/go-gin-wrapper/web
      #- ./go.mod:/go/src/github.com/hiromaily/go-gin-wrapper/go.mod
    environment:
      ENC_KEY: ${ENC_KEY}
      ENC_IV: ${ENC_IV}
    stdin_open: true
    tty: true
    #command: realize start
    command: ./scripts/wait-mysql.sh mysql realize start
