version: '3.9'

services:
  # MySQL
  mysql:
    image: mysql:5.7
    container_name: web-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./build/docker/mysql/conf.d2:/etc/mysql/conf.d
      - ./build/docker/mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gogin
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678

  # Redis
  redis:
    image: 6.0-alpine3.12
    container_name: web-redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass password --appendonly yes
