
[logger]
service = "go-gin"
env = "custom" # dev, prod, custom :for only zap logger
level = "debug" # debug, info, warn, error
is_stacktrace = true

[hash]
salt1 = "foo-bar"
salt2 = "hoge-hoge"

#------------------------------------------------------------------------------
# Server
#------------------------------------------------------------------------------
[server]
is_release = false
scheme = "http"
host = "localhost"
port = 8080

[server.docs]
# set `go-gin-wrapper` path
# this path must be chnaged first for specific environment
path = "${GOPATH}/src/github.com/hiromaily/go-gin-wrapper"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

#------------------------------------------------------------------------------
# Proxy
#------------------------------------------------------------------------------
[proxy]
mode = "no" # no, go-gin-proxy, nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990
web_port = [ 8080, 8081, 8082 ]

#------------------------------------------------------------------------------
# API
#------------------------------------------------------------------------------
[api]
only_ajax = true

[api.cors]
enabled = true
origins = ["localhost:8000"]
headers = ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
methods = ["GET", "OPTIONS"]
credentials = false

[api.header]
enabled = true
header = "X-Custom-Header-Gin"
key = "key12345"

[api.jwt]
mode = 2   #0:off, 1:HMAC, 2:RSA
audience = "hiromaily.com"
secret_code = ""
private_key = "./test/rsakey/jwttest_rsa"
public_key = "./test/rsakey/jwttest_rsa.pub"

#------------------------------------------------------------------------------
# Auth
#------------------------------------------------------------------------------
[auth]
enabled = false

[auth.google]
encrypted = false
client_id = ""
client_secret = ""
call_back_url = "http://localhost:8080/oauth2/google/callback"

[auth.facebook]
encrypted = false
client_id = ""     #app_id
client_secret = "" #app secret
call_back_url = "http://localhost:8080/oauth2/facebook/callback"

#------------------------------------------------------------------------------
# MySQL
#------------------------------------------------------------------------------
[mysql]
encrypted = false
host = "127.0.0.1"
port = 13306
dbname = "gogin"
user = "guestuser"
pass = "secret123"
is_debug_log = true

[mysql.test]
encrypted = false
host = "127.0.0.1"
port = 13306
dbname = "gogin-test"
user = "guestuser"
pass = "secret123"

#------------------------------------------------------------------------------
# Redis for cache
#------------------------------------------------------------------------------
[redis]
encrypted = false
host = "localhost"
port = 6379
pass = ""
is_session = false
is_heroku = false

#------------------------------------------------------------------------------
# Development
#------------------------------------------------------------------------------
[develop]
profile_enable = false
recover_enable = true