#local, heroku, docker, staging, production
environment = "local"

[logger]
service = "go-gin"
env = "custom" # dev, prod, custom :for only zap logger
level = "debug" # debug, info, warn, error
is_stacktrace = true

#------------------------------------------------------------------------------
# Server
#------------------------------------------------------------------------------
[server]
scheme = "http"
host = "localhost"
port = 8080

[server.docs]
path = "/Users/hy/work/go/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

#------------------------------------------------------------------------------
# Proxy
#------------------------------------------------------------------------------
[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990
web_port = [ 8080, 8081, 8082 ]

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

#------------------------------------------------------------------------------
# API
#------------------------------------------------------------------------------
[api]
only_ajax = true

[api.cors]
enabled = true
origins = ["localhost:8000"]
headers = ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
methods = ["GET", "OPTIONS"]
credentials = false

[api.header]
enabled = true
header = "X-Custom-Header-Gin"
key = "key12345"

[api.jwt]
mode = 2   #0:off, 1:HMAC, 2:RSA
secret_code = ""
private_key = "/Users/hy/.ssh/jwt_rsa"
public_key = "/Users/hy/.ssh/jwt_rsa.pub"

#------------------------------------------------------------------------------
# Auth
#------------------------------------------------------------------------------
[auth]
enabled = false

[auth.google]
encrypted = false
client_id = ""
client_secret = ""
call_back_url = "http://localhost:8080/oauth2/google/callback"

[auth.facebook]
encrypted = false
client_id = ""     #app_id
client_secret = "" #app secret
call_back_url = "http://localhost:8080/oauth2/facebook/callback"

#------------------------------------------------------------------------------
# MySQL
#------------------------------------------------------------------------------
[mysql]
encrypted = false
host = "localhost"
port = 3306
dbname = "maindb"
user = "testuser"
pass = "12345678"

[mysql.test]
encrypted = false
host = "localhost"
port = 3306
dbname = "testdb"
user = "testuser"
pass = "12345678"

#------------------------------------------------------------------------------
# Redis for cache
#------------------------------------------------------------------------------
[redis]
encrypted = false
host = "localhost"
port = 6379
pass = ""
session = false

#------------------------------------------------------------------------------
# MongoDB
#------------------------------------------------------------------------------
[mongodb]
encrypted = false
host = "localhost"
port = 27017
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

#------------------------------------------------------------------------------
# AWS
#------------------------------------------------------------------------------
[aws]
encrypted = false
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

#------------------------------------------------------------------------------
# Development
#------------------------------------------------------------------------------
[develop]
profile_enable = false
recover_enable = true