
[logger]
service = "go-gin"
env = "custom" # dev, prod, custom :for only zap logger
level = "debug" # debug, info, warn, error
is_stacktrace = true

#------------------------------------------------------------------------------
# Server
#------------------------------------------------------------------------------
[server]
is_release = false
scheme = "http"
host = "127.0.0.1"
port = 8080

[server.docs]
path = "/home/travis/gopath/src/github.com/hiromaily/go-gin-wrapper"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

#------------------------------------------------------------------------------
# Proxy
#------------------------------------------------------------------------------
[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990
web_port = [ 8080, 8081, 8082 ]

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

#------------------------------------------------------------------------------
# API
#------------------------------------------------------------------------------
[api]
only_ajax = true

[api.cors]
enabled = true
origins = ["localhost:8000"]
headers = ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
methods = ["GET", "OPTIONS"]
credentials = false

[api.header]
enabled = true
header = "X-Custom-Header-Gin"
key = "key12345"

[api.jwt]
mode = 0   #0:off, 1:HMAC, 2:RSA
audience = "hiromaily.com"
secret_code = "secret1234567890"
private_key = "/home/travis/gopath/src/github.com/hiromaily/go-gin-wrapper/test/rsakey/jwttest_rsa"
public_key = "/home/travis/gopath/src/github.com/hiromaily/go-gin-wrapper/test/rsakey/jwttest_rsa.pub"

#------------------------------------------------------------------------------
# Auth
#------------------------------------------------------------------------------
[auth]
enabled = true

[auth.google]
encrypted = true
client_id = "kPmVQs1VcRWa7lm9afOcZzd2wxfLE4Ws441Y5H+MeAs735CVMgSLbUDsqR5vMJSkVLeWP1ScpLmS1hiEvfkTNcOYic3iMojstNDNSQLrUaU="
client_secret = "vWl5RU38iFcid5JI/j610qcp0aoHOEvWI6+Q/QrKRbY="
call_back_url = "http://localhost:8080/oauth2/google/callback"

[auth.facebook]
encrypted = true
client_id = "VZSYxmfcqQFZNUP7Tzchtg=="                         #app_id
client_secret = "aVd1AHW1PVsChVWcI0uhim0etWgg+9Mj2x+puSBTHHM=" #app secret
call_back_url = "http://localhost:8080/oauth2/facebook/callback"

#------------------------------------------------------------------------------
# MySQL
#------------------------------------------------------------------------------
[mysql]
encrypted = false
host = "localhost"
port = 3306
dbname = "gogin"
user = ""
pass = ""
is_debug_log = false

[mysql.test]
encrypted = false
host = "localhost"
port = 3306
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

#------------------------------------------------------------------------------
# Redis for cache
#------------------------------------------------------------------------------
[redis]
encrypted = false
host = "localhost"
port = 6379
pass = "password"
is_session = true
is_heroku = false

#------------------------------------------------------------------------------
# Development
#------------------------------------------------------------------------------
[develop]
profile_enable = false
recover_enable = true